package interpreter.jlox;

public enum TokenType {
    // SINGLE CHARACTER TOKENS
        LEFTPAREN, RIGHTPAREN, LEFTBRACE, RIGHTBRACE, COMMA,
        DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, MOD,
    // SINGLE CHARACTER TOKENS

    // MULTIPLE CHARACTER TOKENS
        NOT, NOT_EQUAL, EQUAL, EQUAL_EQUAL, GREATER_THAN,
        GREATER_THAN_EQUAL, LESS_THAN, LESS_THAN_EQUAL,
    // MULTIPLE CHARACTER TOKENS

    // LITERALS
        IDENTIFIER, STRING, NUMBER,
    // LITERALS

    // KEYWORDS
        AND, CLASS, ELSE, FALSE, FUN, FOR, IF, NIL, OR,
        PRINT, RETURN, SUPER, THIS, TRUE, VAR, WHILE,
    // KEYWORDS

    //EOF
        EOF
    //EOF
}
